name: npm lint

on:
  workflow_dispatch:
  push:
    paths:
      - '**.js'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 8.9
      - run: npm install
      - run: npm run lint
